kind = "web"
previewPath = "/"
title = "NetSwiift"
version = "1.0.0"
id = "artifacts/netswiift"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24484

[services.development]
run = "pnpm --filter @workspace/netswiift run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/netswiift", "run", "build" ]
publicDir = "artifacts/netswiift/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24484"
BASE_PATH = "/"
